const MILLISECONDS_IN_ONE_DAY = 24 * 60 * 60 * 1000

const MILLISECONDS_IN_ONE_HOUR = 60 * 60 * 1000

const MILLISECONDS_IN_ONE_MINUTE = 60 * 1000

const MILLISECONDS_IN_ONE_SECOND = 1000

export {
    MILLISECONDS_IN_ONE_DAY,
    MILLISECONDS_IN_ONE_HOUR,
    MILLISECONDS_IN_ONE_MINUTE,
    MILLISECONDS_IN_ONE_SECOND
}
